title: Pau Barba i Colomer
logo: /assets/2025_Camisa_BW_LR.jpg
description: MSc in Economics and currently completing a second MSc in Data Science, I’m currently pivoting into the data-driven world after several years of hands-on experience in the catering industry. While my professional background lies outside the tech space, I’m bringing a diverse portfolio that shows adaptability along with an expanding technical skill set. Right now, I’m focused on finding meaningful learning opportunities —internships or projects—that will help bridge the gap between academic knowledge and real-world applications.
show_downloads: true
theme: jekyll-theme-minimal
